<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/econ.proto

if (false) {
    /**
     * This class is deprecated. Use CEconItemPreviewDataBlock\Sticker instead.
     * @deprecated
     */
    class CEconItemPreviewDataBlock_Sticker {}
}
class_exists(CEconItemPreviewDataBlock\Sticker::class);
@trigger_error('CEconItemPreviewDataBlock_Sticker is deprecated and will be removed in the next major release. Use CEconItemPreviewDataBlock\Sticker instead', E_USER_DEPRECATED);

