<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/econ.proto

namespace Chescos\CsProto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>CEconItemPreviewDataBlock</code>
 */
class CEconItemPreviewDataBlock extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 accountid = 1;</code>
     */
    protected $accountid = null;
    /**
     * Generated from protobuf field <code>uint64 itemid = 2;</code>
     */
    protected $itemid = null;
    /**
     * Generated from protobuf field <code>uint32 defindex = 3;</code>
     */
    protected $defindex = null;
    /**
     * Generated from protobuf field <code>uint32 paintindex = 4;</code>
     */
    protected $paintindex = null;
    /**
     * Generated from protobuf field <code>uint32 rarity = 5;</code>
     */
    protected $rarity = null;
    /**
     * Generated from protobuf field <code>uint32 quality = 6;</code>
     */
    protected $quality = null;
    /**
     * Generated from protobuf field <code>uint32 paintwear = 7;</code>
     */
    protected $paintwear = null;
    /**
     * Generated from protobuf field <code>uint32 paintseed = 8;</code>
     */
    protected $paintseed = null;
    /**
     * Generated from protobuf field <code>uint32 killeaterscoretype = 9;</code>
     */
    protected $killeaterscoretype = null;
    /**
     * Generated from protobuf field <code>uint32 killeatervalue = 10;</code>
     */
    protected $killeatervalue = null;
    /**
     * Generated from protobuf field <code>string customname = 11;</code>
     */
    protected $customname = null;
    /**
     * Generated from protobuf field <code>repeated .CEconItemPreviewDataBlock.Sticker stickers = 12;</code>
     */
    private $stickers;
    /**
     * Generated from protobuf field <code>uint32 inventory = 13;</code>
     */
    protected $inventory = null;
    /**
     * Generated from protobuf field <code>uint32 origin = 14;</code>
     */
    protected $origin = null;
    /**
     * Generated from protobuf field <code>uint32 questid = 15;</code>
     */
    protected $questid = null;
    /**
     * Generated from protobuf field <code>uint32 dropreason = 16;</code>
     */
    protected $dropreason = null;
    /**
     * Generated from protobuf field <code>uint32 musicindex = 17;</code>
     */
    protected $musicindex = null;
    /**
     * Generated from protobuf field <code>int32 entindex = 18;</code>
     */
    protected $entindex = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $accountid
     *     @type int|string $itemid
     *     @type int $defindex
     *     @type int $paintindex
     *     @type int $rarity
     *     @type int $quality
     *     @type int $paintwear
     *     @type int $paintseed
     *     @type int $killeaterscoretype
     *     @type int $killeatervalue
     *     @type string $customname
     *     @type \Chescos\CsProto\CEconItemPreviewDataBlock\Sticker[]|\Google\Protobuf\Internal\RepeatedField $stickers
     *     @type int $inventory
     *     @type int $origin
     *     @type int $questid
     *     @type int $dropreason
     *     @type int $musicindex
     *     @type int $entindex
     * }
     */
    public function __construct($data = NULL) {
        \Chescos\CsProto\Econ::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 accountid = 1;</code>
     * @return int
     */
    public function getAccountid()
    {
        return isset($this->accountid) ? $this->accountid : 0;
    }

    public function hasAccountid()
    {
        return isset($this->accountid);
    }

    public function clearAccountid()
    {
        unset($this->accountid);
    }

    /**
     * Generated from protobuf field <code>uint32 accountid = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setAccountid($var)
    {
        GPBUtil::checkUint32($var);
        $this->accountid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 itemid = 2;</code>
     * @return int|string
     */
    public function getItemid()
    {
        return isset($this->itemid) ? $this->itemid : 0;
    }

    public function hasItemid()
    {
        return isset($this->itemid);
    }

    public function clearItemid()
    {
        unset($this->itemid);
    }

    /**
     * Generated from protobuf field <code>uint64 itemid = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setItemid($var)
    {
        GPBUtil::checkUint64($var);
        $this->itemid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 defindex = 3;</code>
     * @return int
     */
    public function getDefindex()
    {
        return isset($this->defindex) ? $this->defindex : 0;
    }

    public function hasDefindex()
    {
        return isset($this->defindex);
    }

    public function clearDefindex()
    {
        unset($this->defindex);
    }

    /**
     * Generated from protobuf field <code>uint32 defindex = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setDefindex($var)
    {
        GPBUtil::checkUint32($var);
        $this->defindex = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 paintindex = 4;</code>
     * @return int
     */
    public function getPaintindex()
    {
        return isset($this->paintindex) ? $this->paintindex : 0;
    }

    public function hasPaintindex()
    {
        return isset($this->paintindex);
    }

    public function clearPaintindex()
    {
        unset($this->paintindex);
    }

    /**
     * Generated from protobuf field <code>uint32 paintindex = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setPaintindex($var)
    {
        GPBUtil::checkUint32($var);
        $this->paintindex = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 rarity = 5;</code>
     * @return int
     */
    public function getRarity()
    {
        return isset($this->rarity) ? $this->rarity : 0;
    }

    public function hasRarity()
    {
        return isset($this->rarity);
    }

    public function clearRarity()
    {
        unset($this->rarity);
    }

    /**
     * Generated from protobuf field <code>uint32 rarity = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setRarity($var)
    {
        GPBUtil::checkUint32($var);
        $this->rarity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 quality = 6;</code>
     * @return int
     */
    public function getQuality()
    {
        return isset($this->quality) ? $this->quality : 0;
    }

    public function hasQuality()
    {
        return isset($this->quality);
    }

    public function clearQuality()
    {
        unset($this->quality);
    }

    /**
     * Generated from protobuf field <code>uint32 quality = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setQuality($var)
    {
        GPBUtil::checkUint32($var);
        $this->quality = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 paintwear = 7;</code>
     * @return int
     */
    public function getPaintwear()
    {
        return isset($this->paintwear) ? $this->paintwear : 0;
    }

    public function hasPaintwear()
    {
        return isset($this->paintwear);
    }

    public function clearPaintwear()
    {
        unset($this->paintwear);
    }

    /**
     * Generated from protobuf field <code>uint32 paintwear = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setPaintwear($var)
    {
        GPBUtil::checkUint32($var);
        $this->paintwear = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 paintseed = 8;</code>
     * @return int
     */
    public function getPaintseed()
    {
        return isset($this->paintseed) ? $this->paintseed : 0;
    }

    public function hasPaintseed()
    {
        return isset($this->paintseed);
    }

    public function clearPaintseed()
    {
        unset($this->paintseed);
    }

    /**
     * Generated from protobuf field <code>uint32 paintseed = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setPaintseed($var)
    {
        GPBUtil::checkUint32($var);
        $this->paintseed = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 killeaterscoretype = 9;</code>
     * @return int
     */
    public function getKilleaterscoretype()
    {
        return isset($this->killeaterscoretype) ? $this->killeaterscoretype : 0;
    }

    public function hasKilleaterscoretype()
    {
        return isset($this->killeaterscoretype);
    }

    public function clearKilleaterscoretype()
    {
        unset($this->killeaterscoretype);
    }

    /**
     * Generated from protobuf field <code>uint32 killeaterscoretype = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setKilleaterscoretype($var)
    {
        GPBUtil::checkUint32($var);
        $this->killeaterscoretype = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 killeatervalue = 10;</code>
     * @return int
     */
    public function getKilleatervalue()
    {
        return isset($this->killeatervalue) ? $this->killeatervalue : 0;
    }

    public function hasKilleatervalue()
    {
        return isset($this->killeatervalue);
    }

    public function clearKilleatervalue()
    {
        unset($this->killeatervalue);
    }

    /**
     * Generated from protobuf field <code>uint32 killeatervalue = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setKilleatervalue($var)
    {
        GPBUtil::checkUint32($var);
        $this->killeatervalue = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string customname = 11;</code>
     * @return string
     */
    public function getCustomname()
    {
        return isset($this->customname) ? $this->customname : '';
    }

    public function hasCustomname()
    {
        return isset($this->customname);
    }

    public function clearCustomname()
    {
        unset($this->customname);
    }

    /**
     * Generated from protobuf field <code>string customname = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setCustomname($var)
    {
        GPBUtil::checkString($var, True);
        $this->customname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .CEconItemPreviewDataBlock.Sticker stickers = 12;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getStickers()
    {
        return $this->stickers;
    }

    /**
     * Generated from protobuf field <code>repeated .CEconItemPreviewDataBlock.Sticker stickers = 12;</code>
     * @param \Chescos\CsProto\CEconItemPreviewDataBlock\Sticker[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setStickers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Chescos\CsProto\CEconItemPreviewDataBlock\Sticker::class);
        $this->stickers = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 inventory = 13;</code>
     * @return int
     */
    public function getInventory()
    {
        return isset($this->inventory) ? $this->inventory : 0;
    }

    public function hasInventory()
    {
        return isset($this->inventory);
    }

    public function clearInventory()
    {
        unset($this->inventory);
    }

    /**
     * Generated from protobuf field <code>uint32 inventory = 13;</code>
     * @param int $var
     * @return $this
     */
    public function setInventory($var)
    {
        GPBUtil::checkUint32($var);
        $this->inventory = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 origin = 14;</code>
     * @return int
     */
    public function getOrigin()
    {
        return isset($this->origin) ? $this->origin : 0;
    }

    public function hasOrigin()
    {
        return isset($this->origin);
    }

    public function clearOrigin()
    {
        unset($this->origin);
    }

    /**
     * Generated from protobuf field <code>uint32 origin = 14;</code>
     * @param int $var
     * @return $this
     */
    public function setOrigin($var)
    {
        GPBUtil::checkUint32($var);
        $this->origin = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 questid = 15;</code>
     * @return int
     */
    public function getQuestid()
    {
        return isset($this->questid) ? $this->questid : 0;
    }

    public function hasQuestid()
    {
        return isset($this->questid);
    }

    public function clearQuestid()
    {
        unset($this->questid);
    }

    /**
     * Generated from protobuf field <code>uint32 questid = 15;</code>
     * @param int $var
     * @return $this
     */
    public function setQuestid($var)
    {
        GPBUtil::checkUint32($var);
        $this->questid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 dropreason = 16;</code>
     * @return int
     */
    public function getDropreason()
    {
        return isset($this->dropreason) ? $this->dropreason : 0;
    }

    public function hasDropreason()
    {
        return isset($this->dropreason);
    }

    public function clearDropreason()
    {
        unset($this->dropreason);
    }

    /**
     * Generated from protobuf field <code>uint32 dropreason = 16;</code>
     * @param int $var
     * @return $this
     */
    public function setDropreason($var)
    {
        GPBUtil::checkUint32($var);
        $this->dropreason = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 musicindex = 17;</code>
     * @return int
     */
    public function getMusicindex()
    {
        return isset($this->musicindex) ? $this->musicindex : 0;
    }

    public function hasMusicindex()
    {
        return isset($this->musicindex);
    }

    public function clearMusicindex()
    {
        unset($this->musicindex);
    }

    /**
     * Generated from protobuf field <code>uint32 musicindex = 17;</code>
     * @param int $var
     * @return $this
     */
    public function setMusicindex($var)
    {
        GPBUtil::checkUint32($var);
        $this->musicindex = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 entindex = 18;</code>
     * @return int
     */
    public function getEntindex()
    {
        return isset($this->entindex) ? $this->entindex : 0;
    }

    public function hasEntindex()
    {
        return isset($this->entindex);
    }

    public function clearEntindex()
    {
        unset($this->entindex);
    }

    /**
     * Generated from protobuf field <code>int32 entindex = 18;</code>
     * @param int $var
     * @return $this
     */
    public function setEntindex($var)
    {
        GPBUtil::checkInt32($var);
        $this->entindex = $var;

        return $this;
    }

}

