<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/econ.proto

namespace Chescos\CsProto;

if (false) {
    /**
     * This class is deprecated. Use Chescos\CsProto\CEconItemPreviewDataBlock\Sticker instead.
     * @deprecated
     */
    class CEconItemPreviewDataBlock_Sticker {}
}
class_exists(CEconItemPreviewDataBlock\Sticker::class);
@trigger_error('Chescos\CsProto\CEconItemPreviewDataBlock_Sticker is deprecated and will be removed in the next major release. Use Chescos\CsProto\CEconItemPreviewDataBlock\Sticker instead', E_USER_DEPRECATED);

