<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/market.proto

namespace Chescos\CsProto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>MarketAssetPropertyFilter</code>
 */
class MarketAssetPropertyFilter extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional uint32 property_id = 1;</code>
     */
    protected $property_id = null;
    /**
     * Generated from protobuf field <code>optional float float_min = 2;</code>
     */
    protected $float_min = null;
    /**
     * Generated from protobuf field <code>optional float float_max = 3;</code>
     */
    protected $float_max = null;
    /**
     * Generated from protobuf field <code>optional int64 int_min = 4;</code>
     */
    protected $int_min = null;
    /**
     * Generated from protobuf field <code>optional int64 int_max = 5;</code>
     */
    protected $int_max = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $property_id
     *     @type float $float_min
     *     @type float $float_max
     *     @type int|string $int_min
     *     @type int|string $int_max
     * }
     */
    public function __construct($data = NULL) {
        \Chescos\CsProto\Metadata\Market::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional uint32 property_id = 1;</code>
     * @return int
     */
    public function getPropertyId()
    {
        return isset($this->property_id) ? $this->property_id : 0;
    }

    public function hasPropertyId()
    {
        return isset($this->property_id);
    }

    public function clearPropertyId()
    {
        unset($this->property_id);
    }

    /**
     * Generated from protobuf field <code>optional uint32 property_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPropertyId($var)
    {
        GPBUtil::checkUint32($var);
        $this->property_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional float float_min = 2;</code>
     * @return float
     */
    public function getFloatMin()
    {
        return isset($this->float_min) ? $this->float_min : 0.0;
    }

    public function hasFloatMin()
    {
        return isset($this->float_min);
    }

    public function clearFloatMin()
    {
        unset($this->float_min);
    }

    /**
     * Generated from protobuf field <code>optional float float_min = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setFloatMin($var)
    {
        GPBUtil::checkFloat($var);
        $this->float_min = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional float float_max = 3;</code>
     * @return float
     */
    public function getFloatMax()
    {
        return isset($this->float_max) ? $this->float_max : 0.0;
    }

    public function hasFloatMax()
    {
        return isset($this->float_max);
    }

    public function clearFloatMax()
    {
        unset($this->float_max);
    }

    /**
     * Generated from protobuf field <code>optional float float_max = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setFloatMax($var)
    {
        GPBUtil::checkFloat($var);
        $this->float_max = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int64 int_min = 4;</code>
     * @return int|string
     */
    public function getIntMin()
    {
        return isset($this->int_min) ? $this->int_min : 0;
    }

    public function hasIntMin()
    {
        return isset($this->int_min);
    }

    public function clearIntMin()
    {
        unset($this->int_min);
    }

    /**
     * Generated from protobuf field <code>optional int64 int_min = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setIntMin($var)
    {
        GPBUtil::checkInt64($var);
        $this->int_min = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int64 int_max = 5;</code>
     * @return int|string
     */
    public function getIntMax()
    {
        return isset($this->int_max) ? $this->int_max : 0;
    }

    public function hasIntMax()
    {
        return isset($this->int_max);
    }

    public function clearIntMax()
    {
        unset($this->int_max);
    }

    /**
     * Generated from protobuf field <code>optional int64 int_max = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setIntMax($var)
    {
        GPBUtil::checkInt64($var);
        $this->int_max = $var;

        return $this;
    }

}

